<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Прикладная-статистика.-ДЗ-3." data-toc-modified-id="Прикладная-статистика.-ДЗ-3.-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Прикладная статистика. ДЗ 3.</a></span></li><li><span><a href="#Академия-Аналитиков-Авито" data-toc-modified-id="Академия-Аналитиков-Авито-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Академия Аналитиков Авито</a></span><ul class="toc-item"><li><span><a href="#Задача-1-(2-балла)" data-toc-modified-id="Задача-1-(2-балла)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Задача 1 (2 балла)</a></span><ul class="toc-item"><li><span><a href="#На-зачет" data-toc-modified-id="На-зачет-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>На зачет</a></span></li></ul></li><li><span><a href="#Задача-2-(4-балла)" data-toc-modified-id="Задача-2-(4-балла)-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Задача 2 (4 балла)</a></span></li><li><span><a href="#Задача-3-(3-балла)" data-toc-modified-id="Задача-3-(3-балла)-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Задача 3 (3 балла)</a></span><ul class="toc-item"><li><span><a href="#На-зачет" data-toc-modified-id="На-зачет-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>На зачет</a></span></li></ul></li><li><span><a href="#Задача-4-(4-балла)" data-toc-modified-id="Задача-4-(4-балла)-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Задача 4 (4 балла)</a></span></li><li><span><a href="#Задача-5-(4-балла)" data-toc-modified-id="Задача-5-(4-балла)-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Задача 5 (4 балла)</a></span></li><li><span><a href="#Задача-6.A-(2-балла)" data-toc-modified-id="Задача-6.A-(2-балла)-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Задача 6.A (2 балла)</a></span><ul class="toc-item"><li><span><a href="#На-зачет" data-toc-modified-id="На-зачет-2.6.1"><span class="toc-item-num">2.6.1&nbsp;&nbsp;</span>На зачет</a></span></li></ul></li><li><span><a href="#Задача-6.B-(4-балла)" data-toc-modified-id="Задача-6.B-(4-балла)-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Задача 6.B (4 балла)</a></span></li><li><span><a href="#Задача-7*-(2-балла)" data-toc-modified-id="Задача-7*-(2-балла)-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Задача 7* (2 балла)</a></span></li></ul></li></ul></div>

# Прикладная статистика. ДЗ 3.
# Академия Аналитиков Авито


__Правила:__
- Жесткий дедлайн: **2022-02-27 17:59:59**. 
- Ответ и обсуждение решения — в телеграме.

- Выполненную работу нужно отправить
    - в чатик HW3-<ваше имя> через бота @AAA_stats23_bot
- В качестве решения нужно отправить файл ipynb. Ссылка на интернет-ресурсы не принимается. Не публикуйте решения в открытом доступе!
- Для выполнения задания используйте этот ноутбук в качествие основы, ничего не удаляя из него. **При этом можно добавлять новые ячейки!**
- в ячейках с комменарием `#Автопроверка` нужно заполнить содержимое функций и классов (если есть), которые будут уже объявлены в этой ячейке. При этом:
    - Нельзя убрирать или переставять `#Автопроверка` в ячейке. 
    - Нельзя менять сигнатуру и возвращаемое значение функций. То есть добавлять любой код можно, но удалять, что уже написано - нельзя.
    - Нельзя ничего импортировать в таких ячейках. Все доступные для использования библиотеки будут указаны заранее. Такие слова, как `import`, `globals`, `locals`, `eval`, `exec` также нельзя использовать внутри ячеек.
    - Нельзя использовать библиотеки, кроме тех, что указаны в задании. Ваш код должен работать именно с эти набором библиотек без любого дополнительного импорта!
    - Нельзя использовать код из других ячеек ноутбука (кроме ячейки с импортом, в которой указаны все доступные библиотеки). Единственное исключение - если вы проставите в начало такой ячейки слово `#Автопроверка`. Тогда вы можете использовать код из этой ячейки.
    - В случае нарушения этого правила автопроверка будет провалена и вы не получите часть баллов за задачу. 
    - В случае, если есть несколько ячеек автопроверки, то в каждой такой ячейке можно использовать созданные вами функции (или классы) из других ячеек автопроверки.

## Задача 1 (2 балла)

### На зачет

Мы проводили промо-акцию два раза.

- В первый раз мы отправили 38 писем, из них 26 получателей перешли по ссылке.

- Во второй раз мы отправили уже 98 писем, и из получателей по ссылке перешли 42.

С помощью критерия хи-квадрат определить, насколько значимо изменение CTR между акциями. Можем ли мы делать вывод о том, что информирование во второй промо-акции хуже, чем информирование в первой? Почему?

In [1]:
import pandas as pd

pd.DataFrame(
    [[12, 26, 38], [56, 42, 98], [68, 68, 136]], 
     index=['Первый раз', 'Второй раз', 'Всего'], 
     columns=['Не перешли', 'Перешли', 'Всего'],
)

Не перешли  Перешли  Всего
Первый раз          12       26     38
Второй раз          56       42     98
Всего               68       68    136

Объём выборки в первом и втором случае достаточно большой >=30, также частота каждой ячейки >=10, что дает нам возможность использовать критерий хи-квадрат без поправок.

Так как у нас распределение дискретное, и так как мы сравниваем два эмпирических распределения, тогда число степеней свободы будет равно (кол-во столбцов - 1)(кол-во строк - 1) = (2 - 1)(2 - 1) = 1

При уровне значимости 0.05 проверим следующую гипотезу:

$\textbf{H_0:}$ сущеественных различий между первым и вторым разом проведения акции нет. CTR существенно не различается от раза проведения акции<br>
$\textbf{H_1:}$ различия есть

Посторим таблицу с теоретическими частотами:

In [2]:
pd.DataFrame(
    [[68*38/136, 68*38/136, 38], [68*98/136, 68*98/136, 98], [68, 68, 136]], 
     index=['Первый раз', 'Второй раз', 'Всего'], 
     columns=['Не перешли', 'Перешли', 'Всего'],
)

Не перешли  Перешли  Всего
Первый раз        19.0     19.0     38
Второй раз        49.0     49.0     98
Всего             68.0     68.0    136

Далее мы можем рассчитать эмперическое значение критерия - $\chi^2_{эмп} = \sum^n_{i=1}(X_{1} - X_{2})^2 / X_{2}$

In [3]:
print('Эмпирическое значение критерия:', (12 - 19)**2/19 + (26 - 19)**2/19 + (56 - 49)**2/49 + (42 - 49)**2/49)
print('Теоретическое значение критерия (критическое значение) при уровне значимости alpha = 0.05:', 3.84)

Эмпирическое значение критерия: 7.157894736842105
Теоретическое значение критерия (критическое значение) при уровне значимости alpha = 0.05: 3.84


Так как эмпирическое значение больше критического, следовательно, мы склоняемся в сторону альтернативной гипотезы: различия между проведениями акции есть. О выполнении гипотезы $H_0$ ничего сказать нельзя

Решим тоже самое при помощи библиотеки **scipy**:

In [4]:
from scipy import stats

stats.chi2_contingency([[12, 26], [56, 42]], correction=False)

(7.157894736842105,
 0.007463474476521292,
 1,
 array([[19., 19.],
        [49., 49.]]))

Можно заметить, что таблица частот получилась абсолютно такой же.

Значение статистики хи-квадрат такое же.

pvalue = 0.012979820360836461

Были поставлены следующие вопросы:<br>
_С помощью критерия хи-квадрат определить, насколько значимо изменение CTR между акциями. Можем ли мы делать вывод о том, что информирование во второй промо-акции хуже, чем информирование в первой? Почему?_

**Вывод:** С помощью критерия хи-квадрат мы определили, что есть существенные различия между акциями. Но критерий хи-квадрат не может говорить о том было лучше в первый или второй раз, поскольку он измеряет общее различие между наблюдаемыми распределениями.

При этом наш способ проверки не внушает доверие, так как сравниваемые частоты были не одного размера. А также из условия не очень понятно, если это были зависимые сопоставлемые группы, то такой тест не следовало бы проводить.

## Задача 2 (4 балла)

Реализовать критерий хи-квадрат для таблиц сопряженности $N \cdot M$.

- Условия применимости прверять не надо,  критерий будет проверяться на выборках больших размеров. 

Какими библиотеками вы можете пользоваться:
```
import numpy as np
from collections import namedtuple
from scipy.stats import chi2
```

In [5]:
import numpy as np
from collections import namedtuple
from scipy.stats import chi2

In [6]:
#Автопроверка

MyСhi2Results = namedtuple('MyСhi2Results', 
                                  ['is_rejected', 'pvalue'])


def my_chi2_for_contingency_tables(sample_A: list, sample_B: list, alpha: float = 0.05):
    """
    Параметры:
    - sample_A: первая выборка
    - sample_B: вторая выборка
    - alpha: уровень значимости критерия.
        
    Возвращает:
    - MyСhi2Results с полями:
        - is_rejected: bool
            - отверглась или нет гипотеза H_0 на уровне значимости alpha
        - pvalue: float
    """
    is_rejected = None
    pvalue = None
    
    k = 5 # корзины для выборки sample_A
    m = 5 # корзины для выборки sample_B
    
    # Разобъем sample_A и sample_B на k, m корзин соответсвенно, 
    # диапазоны которых будут равны между собой и протягиваться от мин до макс значения
    A = sorted(sample_A)
    B = sorted(sample_B)
    
    # считаем диапазоны для sample_A
    step_A = (A[-1] - A[0]) / k
    delta_A = [A[0]]
    for i in range(1, k):
        delta_A.append(delta_A[-1] + step_A)
    delta_A.append(A[-1])
    
    # считаем диапазоны для sample_B
    step_B = (B[-1] - B[0]) / m
    delta_B = [B[0]]
    for i in range(1, k):
        delta_B.append(delta_B[-1] + step_B)
    delta_B.append(B[-1])
    
    # считаем частоту попадания в каждый из диапазонов для sample_A
    frequency_A = [0]*k
    for v in A:
        for ind, delta in enumerate(delta_A[1:]):
            if v <= delta:
                frequency_A[ind] += 1
                break
                
    # считаем частоту попадания в каждый из диапазонов для sample_B            
    frequency_B = [0]*m
    for v in B:
        for ind, delta in enumerate(delta_B[1:]):
            if v <= delta:
                frequency_B[ind] += 1
                break
    
    AB = []
    for i in range(len(A)):
        AB.append((sample_A[i], sample_B[i]))
    
    frequencies = [[0] * m for i in range(k)]
    
    # считаем совместную частоту попадания
    for a, b in AB:
        for ind, delta in enumerate(delta_A[1:]):
            if a <= delta:
                ind_A = ind
                break
        for ind, delta in enumerate(delta_B[1:]):
            if b <= delta:
                ind_B = ind
                break
        frequencies[ind_A][ind_B] += 1
    
    n = len(sample_A)
    
    # Считаем статистику
    tau = 0
    for ind_A, line in enumerate(frequencies):
        for ind_B, v in enumerate(line):
            term = ((v - (frequency_A[ind_A]*frequency_B[ind_B])/n)**2) / (frequency_A[ind_A]*frequency_B[ind_B])
            tau += term
    tau *= n
    
    pvalue = 1 - chi2.cdf(x=tau, df=(m-1)*(k-1))
    if pvalue < alpha:
        is_rejected = True
    else:
        is_rejected = False

    return frequencies, MyСhi2Results(is_rejected, pvalue)

<div class="alert alert-info">  

Дима Лунин в чатике сказал, что можно не париться на счет производительности, поэтому не оптимизировал код, хотя тут можно улучшить

Также не было указания к тому, чтобы техать теорию, просто оставлю [ссылку](https://tvims.nsu.ru/chernova/ms/lec/node49.html), которой пользовался </div> 

## Задача 3 (3 балла)

### На зачет

Компьютер периодически отправляет запросы на сервер. Иногда сервер бывает недоступен, поэтому компьютер с некоторым интервалом повторяет запросы до тех пор, пока сервер не ответит. Известно, что 52 запроса дошли с первой попытки, 31 &mdash; со второй, 3 &mdash;  с третьей, а для доставки еще 5 запросов потребовалось более 4  попыток. Верно ли, что сервер получает запросы с вероятностью 2/3?

**Задачу нужно решить теоретически!**

Можно воспользоваться лишь библиотекой `from scipy.stats import chi2`.

Сервер получает запросы с вероятностью 2/3, соответственно не получает запрос с вероятностью 1/3. Тогда веротяность, что запрос дойдет:
- С первого раза - $2/3$
- Со второго раза - $2/3 * 1/3$
- С третьего раза - $2/3 * 1/3 * 1/3$
- С четвертого раза и более - $1 - (2/3 + 2/3 * 1/3 + 2/3 * 1/3 * 1/3)$

При уровне значимости 0.05 проверим следующую гипотезу:

$\textbf{H_0:}$ сервер получает запросы с вероятностью 2/3<br>
$\textbf{H_1:}$ $H_0$ неверна

In [7]:
pd.DataFrame(
    [[52, 31, 3, 5], ['2/3*91', '2/9*91', '2/27*91', '1/27*91']], 
     index=['Эмпирическая частота', 'Теоретическая частота'], 
     columns=['С первого раза', 'Со второго раза', 'С третьего раза', 'Более чем с тертьего'],
)

С первого раза Со второго раза С третьего раза  \
Эмпирическая частота              52              31               3   
Теоретическая частота         2/3*91          2/9*91         2/27*91   

                      Более чем с тертьего  
Эмпирическая частота                     5  
Теоретическая частота              1/27*91

Мы видим проблему - частота ячеек не везде больше 5, поэтому стоит объеденить ячейки запросов дошедших с третьего раз и более, чем с третьего.

In [8]:
pd.DataFrame(
    [[52, 31, 8], ['2/3*91', '2/9*91', '1/9*91']], 
     index=['Эмпирическая частота', 'Теоретическая частота'], 
     columns=['С первого раза', 'Со второго раза', 'С третьего разаи более'],
)

С первого раза Со второго раза С третьего разаи более
Эмпирическая частота              52              31                      8
Теоретическая частота         2/3*91          2/9*91                 1/9*91

Тогда нам нужно получить значение хи-квадрат $\chi^2_{} = \sum^n_{i=1}(X_{эмп} - X_{теор})^2 / X_{теор}$

И далее сравнить полученное значение со значением хи-квадрат для 2 степеней свобод, при уровне значимости 0.05

In [9]:
from scipy.stats import chi2

1 - chi2.cdf(x=(52 - 2*91/3)**2 / (2*91/3) + (31 - 2*91/9)**2 / (2*91/9) + (8 - 91/9)**2 / (91/9), df=3 - 1)

0.02443989449617623

**Вывод:**  pvalue < alpha = 0.05, следовательно, мы склоняемся в сторону альтернативной гипотезы: сервер получает запросы с иной вероятностью, не равной 2/3. О выполнении гипотезы  $𝐻_0$ ничего сказать нельзя.

(Можно отметить, что pvalue около 0.025, что не сильно близко к 0)

## Задача 4 (4 балла)


Компания по производству коромов для попугаев провела опрос среди 5000 владельцев попугаев о том, что предпочитают есть их питомцы. По результатам опроса оказалось, что 1010 птиц предпочитают глазированные сырки, 2200 &mdash; фрукты, 950 &mdash; семечки и крупы, а все остальные предпочитают колбасу. Компания сделала предположение, что вероятности предпочтения этих видов еды равны $\theta, 2\theta, \theta, 1-4\theta$, где $\theta \in (0, 1/4)$. Верно ли данное предположение?

**Задачу нужно решить теоретически!**

Можно воспользоваться лишь библиотекой `from scipy.stats import chisquare`.

P.S. Задача появилась из рациона попугая составителя домашнего задания...

При уровне значимости 0.05 проверим следующую гипотезу:

$\textbf{H_0:}$ Вероятности предпочтения видов равны $\theta, 2\theta, \theta, 1-4\theta$, где $\theta \in (0, 1/4)$<br>
$\textbf{H_1:}$ $H_0$ неверна

In [10]:
pd.DataFrame(
    [[1010, 2200, 950, 840], ['$\theta$', '$2\theta$', '$\theta$', '1-4*$\theta$']], 
     index=['Эмпирическая частота', 'Теоретическая частота / 5000'], 
     columns=['Глазированные сырки', 'Фрукты', 'Семечки и крупы', 'Колбаса'],
)

Глазированные сырки     Фрукты Семечки и крупы  \
Эмпирическая частота                        1010       2200             950   
Теоретическая частота / 5000            $\theta$  $2\theta$        $\theta$   

                                   Колбаса  
Эмпирическая частота                   840  
Теоретическая частота / 5000  1-4*$\theta$

Для того, чтобы критерий хи-квадрат работал на задаче с оценкой параметров, нам нужно оценить параметр с помощью метода максимального правдоподобия.

$P = \theta^{1010} * (2\theta)^{2200} * \theta^{950} * (1-4\theta)^{840}$

$ln(P) = ln(\theta)*1010 + ln(2)*2200 + ln(\theta)* 2200 + ln(\theta)*950 + ln(1-4\theta)*840$

Далее возьмем производную и приравняем к нулю:

$(1010 + 2200 + 950) * (1/\theta) + 840 * (1/(1-4\theta))*(-4) = 0$

$4160 * (1-4\theta) = 3360 * \theta$

Получим $\theta = 4160 / (3360 + 4160*4) = 0.208$ Данное значение попадает в предполагаемый интервал.

Так как мы оценили один параметр, следовательно, будем смотреть на хи-квадрат со степенями свобод: (4 - 1 - 1) (ddof=1)

In [11]:
from scipy.stats import chisquare

chisquare([1010, 2200, 950, 840], f_exp=[0.208*5000, 2*0.208*5000, 0.208*5000, 0.168*5000], ddof=1)

Power_divergenceResult(statistic=15.576923076923077, pvalue=0.00041449007074133005)

**Вывод:** pvalue < alpha = 0.05, следовательно, основания принять нулевую гипотезу нет, склоняемся в сторону альтернативной.

## Задача 5 (4 балла) 

Критерий назовается состоятельным, если его мощность сходится к 1 при $n \rightarrow +\infty$ при любом распределении, соответсвущем альтернативной гипотезе. Докажите сотсоятельность критериев согласия
- A) (2 балла) Колмогорова и
- B*) (2 балла) Хи-квадрат,

проверяющих

$$H_0: F = F_0$$

Где F - функция распределения текущей выборки, $F_0$ - предполагаемая функция распределения.

**Задачу нужно решить теоретически!**

Нам нужно доказать, что вероятность отвергнуть нулевую гипотезу стремится к 1, если верна альтернативная гипотеза.

Как таковое доказательство не могу привести, не успеваю расписать и затехать.

[Вот тут](https://tvims.nsu.ru/chernova/ms/lec/node44.html) есть в общем случае для криериев согласия, отсюда можно выводить для любого критерия.

[Тут](https://scask.ru/d_book_kstat2.php?id=188) есть доказательство для хи-квадрат

## Задача 6.A (2 балла)

### На зачет

Какие критерии однородности вы можете привести на текущий момент? Приведите минимум 4 примера и в каких случаях можно использовать каждый из них?

Критерий однородности, который служит для проверки гипотезы о том, что выбрки сэмплированы из одного и того же распределения.

**Критерий Колмогорова-Смирнова**

$D_{m,n}$- статистика — максимальное расхождение мажду эмпирическими функциями распределения двух случайных величин
$$D_{m,n}= \sup_x|F_B(x) - F_A(x)|$$

Если эта разность значимо велика, распределения считаются различными.

Можно использовать только в случае непрерывных распределений.

**Двухвыборочный критерий Пирсона или Хи-квадрат**

Универсальный критерий для проверки гипотезы о различии распределений двух и более совокупностей.

Есть порог на минимальное количество наблюдаемых значений для каждой категории признака.

**Некий традиционный метод проверки однородности (Например, Критерий Стьюдента + Критерий Фишера)**

Используем t-test для проверки гипотезы о средних<br>
Используем f-test на равенство дисперсий

Если оба подтверждают гипотезу о равентсве, то можно говорить об однородности выборок

**Критерий знаков**
[Можно посмотреть тут](http://datalearning.ru/index.php/textbook?cid=1&mid=4&topic=3)

Из принятия основной гипотезы критерия знаков не следует однородность выборок, а следует лишь возможность однородности. Если же основная гипотеза критерия знаков отклоняется, то отклоняется и гипотеза однородности выборок.

## Задача 6.B (4 балла)

Какой критерий однородности вы стали бы использовать на практике и в каких случаях?

От вас ожидаетя практический ответ на вопрос: будете ли вы в работе использовать этот критерий в качестве критерия однородности? Рассмотрите разные случаи и выборки. 

Сделайте финальный выбор.

Наверное, как неопытный статистик/аналитик можно тратить больше времени и проверять несколькими способами.

Но однозначно если у нас выборка насемплирована из дискретного распределения, то нельзя использовать критерий Колмогорова-Смирнова.

Если у нас данные категориальные или же количественные данные, имеющие дискретное распределения, то стоит воспользоваться критерием хи-квадрат.

Тест Колмогорова-Смирнова хороший, потому, что он чувствителен как к полодению так и к форме распределения, что для нас важно. 

Например, "традиционный метод" может показать равенство дисперсий и равенство мат ожиданий, но не сможет ничего сказать о различии форм.

Одно из интересных применений колмогорова-Смирнова на практике - при разбитие датасета на обучающую/тестовую выборки мы модем проверить будут ли они распределены из одного и того же распределения.

Чем ещё хорош Колмогоров-Смирнов: тем что распределение нормированной статистики не зависит от фнкций F и G. И если распределения выборок неизвестно или же не описывается каким-либо параметрическим семейством распределений, мы можем очень даже удачно его испольщзовать.

Но всё это в случае непрерывного, если же распределение дискретное, тогда можем использовать хи-квадрат.

**Резюме:**

Если мы понимаем, что выборки из непрерывных распределений, тогда будем использовать критерий Колмогорова-Смирнова.

Если же нет уверенности в этом, используем хи-квадрат, учитывая его ограничения на общее количество наблюдений и частоту встречи признаков наблюдаемых величин.

Другие приведенные критерии однородности могут лишь служить в качестве вспомогательной функции, если они выполняются, это нам не будет говорить о том, что точно две выборки из одного распределения, но если условия невыполнены, то это будет говорить о том, что принадлежности к одному распределению нет. В общем, это необходимость, но недостаточность.

Также 100% существует множемство других критериев однородности с которыми ещё предстоит познакомиться, которые будут лучше подходить к той или иной ситуации.

## Задача 7* (2 балла)

Мы знаем, что критерий согласия Колмогорова не работает для дискретных распределений.

Как модифицировать этот критерий, чтобы он начал работать с равномерным дискретным распределением `scipy.stats.randint(1, 7)`? А как поступить с другими распределениями?

[Тут](https://ami.nstu.ru/~headrd/seminar/publik_html/APEP2006_1.htm) есть рассказ как бороться с дискретными распределениями. Но мне не удалось нагуглить какое преобразование Смирнова тут используют.

Также где-то слышал, что для таких переходов дискретное-непрерывное применяется дискретное преобразование Фурье, но могу ошибаться.

И к каждому частному случаю модно придумывать свой определенный метод конвертиции, [например](http://rateli.ru/books/item/f00/s00/z0000013/st012.shtml)